version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: policy_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: policy_management
      MYSQL_USER: policy_user
      MYSQL_PASSWORD: policy_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - policy_network

  # Camunda 8 Self-Managed (Alternative to Cloud)
  zeebe:
    image: camunda/zeebe:8.3.0
    container_name: policy_zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
    volumes:
      - zeebe_data:/usr/local/zeebe/data
    networks:
      - policy_network
    depends_on:
      - elasticsearch

  # Elasticsearch for Camunda
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: policy_elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - policy_network

  # Camunda Operate
  operate:
    image: camunda/operate:8.3.0
    container_name: policy_operate
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - policy_network
    depends_on:
      - zeebe
      - elasticsearch

  # Camunda Tasklist
  tasklist:
    image: camunda/tasklist:8.3.0
    container_name: policy_tasklist
    ports:
      - "8082:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - policy_network
    depends_on:
      - zeebe
      - elasticsearch

volumes:
  mysql_data:
  zeebe_data:
  elasticsearch_data:

networks:
  policy_network:
    driver: bridge
